[package]
name = "nft-lending"
version = "1.0.0"
authors = []

[addresses]
lending_addr='_'

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }
MegaloandonOracle = {local = "../Aptos-NFT-Lending-Oracle"}

[dev-dependencies]
